### ISSUE TITLE
Unhandled Error Event

### ISSUE THREAD

**Issue by nickbewley** [darrinhenein/framer-sketch-boilerplate#1]
Followed the instructions, but for some reason am getting this error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

Am I missing something?

Thanks a ton!

**Comment by darrinhenein** [comment]
Hey @nickbewley! Did you install sketch tools first? 

> 1.  Install sketch-tool $ curl -L https://raw.githubusercontent.com/cognitom/dotfiles/master/lib/sketchtool.sh | sudo sh

**Comment by nickbewley** [comment]
Yes although maybe my network froze.. I am looking at this:

![screen shot 2015-02-17 at 3 43 37 pm](https://cloud.githubusercontent.com/assets/5789940/6239758/c89048ce-b6bb-11e4-82c1-535d46ade939.png)

Thanks a ton for getting back to me!

**Comment by darrinhenein** [comment]
@nickbewley no problem! Hopefully that works, and feel free to close the issue if it does :+1:

**Comment by nickbewley** [comment]
For sure. Installing sketch tools separately did the trick! Thanks for the repo and writeup man!
