### ISSUE TITLE
Not Copying the .png file to build/images

### ISSUE THREAD

**Issue by DavidStrada** [darrinhenein/framer-sketch-boilerplate#3]
Hey there!,

I was testing your script ( thanks for creating it ), however found that sketch task after saving the file it's not exporting the new file to build/images.

It's not generating any errors i checked.

**Comment by DavidStrada** [comment]
I manually inserted a circle.png file onto build/images and it works ( but manually ).

**Comment by darrinhenein** [comment]
Thanks! When you run `gulp`, does it stay running and say something about watching the current folder?

**Comment by DavidStrada** [comment]
Yeah, I mean gulp is running and compiling ( coffee script part ) i even put a console.log() after `pipe(gulp.dest('build/images/')); console.log( “finished building sketch" );`
Thanks,
David

**Comment by DavidStrada** [comment]
Here's the log 

``` console
» gulp watch
[12:04:42] Using gulpfile ~/Code/framer-sketch/gulpfile.js
[12:04:42] Starting 'watch'...
[12:04:43] Finished 'watch' after 183 ms
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.60.100:3000
[BS] Serving files from: build
[BS] Watching files...
[12:04:51] Starting 'sketch'...
finished building sketch
[12:04:51] Finished 'sketch' after 36 ms


```

**Comment by DavidStrada** [comment]
I changed the background color on sketch saved the file.

**Comment by Reklino** [comment]
Having this same issue... Tried gulp-sketch 0.6.0 as well. No error messages. @DavidStrada any luck getting something working?

**Comment by DavidStrada** [comment]
I’m creating my own when i get the initial draft can send you a message when that is done, the problem with this one is not copying the file to src/ folder, ( in case you want to do a PR ) tho.

Thanks,
David

**Comment by Reklino** [comment]
Cool. Keep me posted!

**Comment by rygar** [comment]
I've been having the same troubles. I have a theory that the lack of circle.png in the src directory isn't helping but feels like the main issue is with gulp-sketch and/or how assets.sketch itself is created. If you figure it out, please lemme know. I'll do the same.

**Comment by sebastienbarre** [comment]
Just chiming in, seems to be working as of today, with Sketch 3.7.1, no modifications on my side. 

If the problem persists, maybe try running `sketchtool` manually to debug errors?

```
framer-sketch-boilerplate (master)$ sketchtool list slices src/assets.sketch
{
  "pages" : [
    {
      "id" : "16F2D4DF-EA73-41AC-9B38-BB5700B67C08",
      "name" : "Page 1",
      "bounds" : "2244.000000,-108.000000,178.000000,178.000000",
      "slices" : [
        {
          "rect" : {
            "y" : -108,
            "x" : 2244,
            "width" : 178,
            "height" : 178
          },
          "id" : "10976791-2545-41AE-BF19-11F026395228",
          "influence" : {
            "y" : -108,
            "x" : 2244,
            "width" : 178,
            "height" : 178
          },
          "name" : "circle",
          "trimmed" : {
            "y" : -108,
            "x" : 2244,
            "width" : 178,
            "height" : 178
          },
          "relative" : {
            "y" : -108,
            "x" : 2244,
            "width" : 178,
            "height" : 178
          }
        }
      ]
    }
  ]
}
```

Here is a potential pitfall:

```
framer-sketch-boilerplate (master)$ sketchtool list slices src/assets.sketch
2016-04-19 10:40:25.504 sketchtool[16688:97551] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
```

Above, my Sketch 3.7 had upgraded itself to 3.7.1, but `sketchtool` was not up to date; I installed it manually by running `Sketch.app/Contents/Resources/sketchtool/install.sh`.

Thanks to @darrinhenein for this boilerplate, this is certainly helpful!

**Comment by mattWillis** [comment]
@sebastienbarre this fixed the problem for me. The `sketchtool` version installed by Homebrew must not be up to date. 

My Sketch app was at 3.7.1, and by running the manual install: `Sketch.app/Contents/Resources/sketchtool/install.sh` everything seems to be in order now.

Thanks @Reklino for this boilerplate! It fits in perfectly with my existing tech stack and is going to truly enhance my workflow!

**Comment by darrinhenein** [comment]
Great! I'm going to close this issue as it seems to be working with the latest versions of Sketch and `sketchtool`. Feel free to open new issues if this changes!
